### ISSUE TITLE
License Section 2(b.4) is not legally valid

### ISSUE THREAD

**Issue by spaceclouds42** [queer/GFYPL#13]
[Line in question](https://github.com/queer/GFYPL/blob/7c78d87ea3090bc8d56593af1ad3d4cd4bda730d/GFYPL#L59)

Based on past court cases, what can be licensed is the way in which you do things, not the thing you do. Therefore, regardless of what this license says, people can replicate the function(s) of the licensed material, making this license unenforceable. My suggestion is to remove this clause, thereby making this license (possibly) enforceable.

**Comment by queer** [comment]
The README says that this licence will almost certainly not hold up in court. It's a joke licence / repo. Having it hold up in court is not a huge concern.

**Comment by spaceclouds42** [comment]
True, but it would be nice if something glaring like this wasn't an issue :v

**Comment by a1icja** [comment]
This should probably be closed (js)
