### ISSUE TITLE
Inconsistent use of "license" vs "licence"

### ISSUE THREAD

**Issue by LoganDark** [queer/GFYPL#15]
In the main license text (see https://github.com/queer/GFYPL/blob/mistress/GFYPL), there's mixed use of "license" vs "licence", for example:

- The header uses "licence"...

  https://github.com/queer/GFYPL/blob/8e17452d04ddb5626a56e7fc6d1a84cf0da20ccc/GFYPL#L2

- ...while a later section mentions "licensor" and "licensee"

  https://github.com/queer/GFYPL/blob/8e17452d04ddb5626a56e7fc6d1a84cf0da20ccc/GFYPL#L17-L26

If you can't decide which one to use, perhaps you should make 2 versions, one for "license" and one for "licence", and keep the usage consistent within each one. Would be glad to open a PR for this, but not doing so yet because I don't know if it would be accepted.

**Comment by queer** [comment]
I prefer "licence" to "license" and just missed it in PR review; I'm open to one that fixes the inconsistency ^^

**Comment by LoganDark** [comment]
> I prefer "licence" to "license"

I guess downstream users can just find and replace then if you're not open to having a separate version for it.
